// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOs4wGpALqUAHZK6VfgYW8UOOi97cy-fA',
    appId: '1:1016291592132:web:df622191fce082a0860691',
    messagingSenderId: '1016291592132',
    projectId: 'ai--resume-analyzer',
    authDomain: 'ai--resume-analyzer.firebaseapp.com',
    storageBucket: 'ai--resume-analyzer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5ot8-jESVBSJObeFwKpXfh0LQHeVPBE',
    appId: '1:1016291592132:android:8988355ee6f12e98860691',
    messagingSenderId: '1016291592132',
    projectId: 'ai--resume-analyzer',
    storageBucket: 'ai--resume-analyzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7K2sq3bCcnqVfuIQisuo8dMsab1iLG74',
    appId: '1:1016291592132:ios:9dce43b270313b7a860691',
    messagingSenderId: '1016291592132',
    projectId: 'ai--resume-analyzer',
    storageBucket: 'ai--resume-analyzer.firebasestorage.app',
    iosClientId: '1016291592132-91jahct04oe4q7lc8jiar0932lacvh34.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7K2sq3bCcnqVfuIQisuo8dMsab1iLG74',
    appId: '1:1016291592132:ios:9dce43b270313b7a860691',
    messagingSenderId: '1016291592132',
    projectId: 'ai--resume-analyzer',
    storageBucket: 'ai--resume-analyzer.firebasestorage.app',
    iosClientId: '1016291592132-91jahct04oe4q7lc8jiar0932lacvh34.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOs4wGpALqUAHZK6VfgYW8UOOi97cy-fA',
    appId: '1:1016291592132:web:289afd5938243a0f860691',
    messagingSenderId: '1016291592132',
    projectId: 'ai--resume-analyzer',
    authDomain: 'ai--resume-analyzer.firebaseapp.com',
    storageBucket: 'ai--resume-analyzer.firebasestorage.app',
  );
}
